### PR TITLE
Add a composer.json

### PR DESCRIPTION
**Pull request by mscharley**
Simply adds a basic `composer.json` to identify the project in lieu of using Drupal.org and Drupal Packagist. Allows people to use the port here with Composer-based sites till the port makes it back onto Drupal.org.

### CODE REVIEW

**Comment by Berdir** [comment]
Happy to merge the composer change, but not sure why we need the .gitignore here? dependencies wouldn't be added here anyway?

**Comment by Berdir** [comment]
Note: I've just moved this back to d.o, please provide this as a patch there.

**Comment by mscharley** [comment]
I'm happy to provide a patch on d.o as well if you're still interested, though for me it's irrelevant now. d.o builds composer packages for downstream users for every package release on d.o whether they supply a `composer.json` file or not. Let me know if you want me to provide the patch anyway.

With regards to the gitignore, dependencies should be added to the composer.json as well, otherwise it rather defeats the point of having it. Ultimate Cron 2.x just doesn't have any right now. If you're interested in seeing Composer in action in D8 then checkout https://www.drupal.org/sandbox/mscharley/2629336 and especially https://github.com/mscharley/drupal-heroku-demo which is the demo application for that project.

**Comment by Berdir** [comment]
Yes, dependencies should be added. but those dependencies would not be added to the module folder, they would be added to the top-level vendor folder, that's how composer/class-loading works. Both for the composer manager approach and for the full composer based approach.

Anyway, this moved to d.o now. You're welcome to provide a patch there if you want to, closing this.

**Comment by naveenvalecha** [comment]
> but those dependencies would not be added to the module folder, 

Right! For more detailed information blog link attached https://bojanz.wordpress.com/2015/09/18/d8-composer-definitive-intro/

Anyhow I have filed an issue in d.o. issue queue  https://www.drupal.org/node/2640244

**Pull request closed without merging**
